language: generic
sudo: required
services:
- docker
env:
  global:
  - GIT_SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_2c6847602b1c_key -iv $encrypted_2c6847602b1c_iv
  -in thelab-240901-a3965d3603ea.json.enc -out thelab-240901-a3965d3603ea.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl --version=1.19
- gcloud auth activate-service-account --key-file thelab-240901-a3965d3603ea.json
- gcloud container clusters get-credentials my-cluster-1 --zone=asia-south1-a --project=thelab-240901
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
deploy:
  provider: script
  script: sed -i 's/\r$//' deploy.sh | bash ./deploy.sh
  on:
    branch: main
