sudo: required
services:
- docker
env:
  global:
  - GIT_SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- openssl aes-256-cbc -K $encrypted_ad7ee8c24b7c_key -iv $encrypted_ad7ee8c24b7c_iv
  -in thelab-240901-5411dd5351fb.json.enc -out thelab-240901-5411dd5351fb.json -d
- gcloud auth activate-service-account --key-file thelab-240901-5411dd5351fb.json
- gcloud config set project thelab
- gcloud config set compute/zone asia-south1-a
- gcloud container clusters get-credentials factorial-project-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
